import { Geist, Geist_Mono } from 'next/font/google';
import '../globals.css';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata = {
  title: 'About',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <div>
      <main>{children}</main>
    </div>
  );
}
