import { Geist, Geist_Mono } from 'next/font/google';
// import '../globals.css';

export const metadata = {
  title: 'User',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <div>
      <main>{children}</main>
    </div>
  );
}
